apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-ssd-0
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: hostpath
      - name: BasePath
        value: /volumes/ssd-0
provisioner: openebs.io/local
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
