apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:uYd30pAJ6EIhs+EXCD3LoxsH10AEFjkRChlNuReHjC3ah5vi+KOq0g==,iv:in5ukZ1JpaqWrqVbValSbh4kSyimmAgXRUUONAKY9hs=,tag:CjaI9sLbeIv/FoZ5+56MbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-08T13:15:34Z"
    mac: ENC[AES256_GCM,data:KEyxbxf9HQjdoFNOUaI407YzyEi1I1NBzTZGR0/nTUWXDklcsNoURcaU607kSiXmR9iAbmcGCU/p8PXa1stJBFZskgxwnYc9IsE0OFb7B66/w84NP8QHslg9StLmHuDcjd6cJ+7a0Ax6jBu2YH4pTTkkzZvDBMo0mSbGdmKDRZo=,iv:7xzDZxi997boKYX//WCM2edBzczpaiuimygVkhlv8UQ=,tag:qFgetGNvTdDOXMZ3WzP9Lg==,type:str]
    pgp:
        - created_at: "2021-12-08T13:15:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA452ft8CT80SAQ/8C63wxlBxjiQPqnjVzHSt4T835sF61VzUjDiltFqwQ+qW
            4G5ut9bu1k7582FH02GC27NlGMWkY0hDEeqwZFubmr4enPgb3kNENRfpywfppHpa
            pX+gUWqAMP3EveHSk3p0Kw694H+hgDgRUevtk4IS5I73RRHkiEth48gWDu3v0v8Z
            S+RJx+wdHnyChfm06GlQh3dLEDuC89XSy258tgywA70BjeKASPUpBxOiHhZRTAWZ
            G7225ltdUEGOHBAUTV4bCJNFmxPL2qjki1ZFpDDr9iYG14dVfgPSWUSq2DfSBqtK
            Ls3CSXmNC7vwhV0qW2B/hwiKJ5aLfmyVdyOz965iymzy1aXj3q3aFQDo+O8GjomT
            UZJ+meS0Of18s9b++Fp59X5QvWgmIk+DpcL4TimoNOygIjHMaqejKyB3/A4QRs0U
            wqDUCRU+EbGvVq9EYv3SlYT9k7hT+aI832g6RDYRwaqDQo7jpgAktBEvkmZYyD1u
            UeBvc6QGu93uuYxo0PXFC3K0baA6OdXry9aJgDvgCWYXXjZwK+ScrWg5+FK74vP+
            aOvYmCcU8uPiYix0dF3I2PdkLd4p3P+DZjTH+W+gZu3MZfQMtBBA9mYtVIOxY4+A
            RPV48hlaAJfG0qPXYW8hwO4P0d3JzFSy77xIENyyqAXoJps8OuCv7uAXMIijjhPS
            XgGWD2TlYGds8uIWG8uAhAlRCOqxTS8O0inzNXg4071xVi577IKcOuJnQxH7ga71
            RnYFISlC+zVPjdHYeiSL8rZA+HpMuElUeE6ylf+FxMmj/eDkzb1auRdOwqCLvgI=
            =SeDj
            -----END PGP MESSAGE-----
          fp: A46BCBE5025D400A71759E6947630974DB001607
        - created_at: "2021-12-08T13:15:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzKiqMukNpUtAQ/6AuX5XR5Tte3I5CObOijJWGhetvxmHTX0nUEQijs0+TpZ
            HAxFxsXsGUcM8j0EuAFy2N4gH3jh74ejNccoTC0vthefNkTw9flA7uwt5LJzPAYu
            6S6Ksws5FXTobtIH/ofXdF5+wE2qIgQNUJ9dd1SiZbyavkcbTzokoaKk73cc/nRk
            g77y0bdMeRBWZaTL5qwkghjU0LyVaHL0eQePpcx9HLrJo4SG2YJeeEFt969Hsr2F
            VcQJXt6+LDSgnvA7VdrUqvFpKx63aHlzC5bvtFervmtCFq+aI/QzekbPoZ7pjfaT
            vh4bAXIaMLemY5S9SO2jIB9ZSFuX2Yw1583dYO60ypw9ueTy9zZGGfo+SbmDhpuJ
            ZN7M/J8Mcw/j3mcbqtabLAEIlUhRhf3sjgouU7m3UAAIuFP0r7a25Sq8aaHiW1Pi
            IJ5jLXLchmlGbDfbvw8YWKLPJW9oTAWrL51LTCD7U2YZC3o7Ak21BZV3xihP8tG0
            U4EK3p/Rwff3jpwW4mFkVtN37e3WUoy0drjBx6B0I/lqTjB/pHcI6cgvObF1zWkI
            oz/cGO2oZjELlFVB4fqAtp303EkZBFIQBPZXygTDHpJcfye5dyft6mi33eDsLCP7
            7/Vp8PyhDBCtNMjCVBulxXorAGjytSLq9DNBy7vMlH3gfPf6ZCQAiUvi2KXpxE3S
            XgE40t9WL8eg99CCoQi1mgWoDZ7rIegaHFEtbzgM6F71grhk6V7uMce2HLgVrBry
            JAocTrYE2pcaV5hcfrnrnbRjLnaZ9CKgLvmbTIhsDAAlmhkwU01ctn1erH4lbAY=
            =eC/h
            -----END PGP MESSAGE-----
          fp: 416E502A845A87487EF12661331A5023FC9B89BA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
