kind: Secret
ansible_user: ENC[AES256_GCM,data:3lZpH69z,iv:0dWhl1AQ89k+xP72a9NBtnZ2WIOY05pI5pnIMV9pTDU=,tag:IEBpk4Gx3uIy8FFFAOkkLA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:JFSRMHDUFPPq,iv:IlmcuVfG5WcsvI9JErzBurwGeSTuCsYO4YB0NLLGj/Q=,tag:OVQCDtiFtHIYvm3v51csSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-19T15:12:00Z"
    mac: ENC[AES256_GCM,data:qKHUKxiQ4ZTxVMxWS6XwRoB09AstDYfJOlcxF5Vr3seA2gIICxkN+UOPDW86XeH61zEVXcfeCcbusb3pKRuMYSa7LKE5MORN1HSGvQ7yMSvH7pv5Rs76NOLXCgeIlsOacviAdcN0udditNzVuD8LWcVyNMPlouHRptdN5IjIYxw=,iv:4ksfkdg3gaGHfMwLtIzuM16pt92ynRcccVHXpWsRqQs=,tag:TH1yRTzCG9qDHRcXM22l3g==,type:str]
    pgp:
        - created_at: "2021-11-19T15:12:00Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzKiqMukNpUtARAAo4tLzSOjJEuYltBxRbH9l+yRT+H244cGZHmvc0y3bXlW
            VP2Mv1cgRXuZ3JaQUNDSKKQ3OIfbE2xz7tGNNHjkQiMeNSNRW7F+m5kVn/QAWPTZ
            K6ToQ0nHdg3FZqJ/kydd3wqFEtYdXJEefhp1VpYqCMGQiC99ZGGlP/PxeXzCMhX3
            vAgFSb8J3Zd+kWHIR/Ii4jB2m0Umqry6d9WdVZK+JN0dN2AUiMsgq9Eqv1erWzrh
            rrXR6ECANYwhXQ/3F4BtwyqTT5YfcGygZdRy+qg/wW69peXGbwStY7D+EKzIYabY
            tYMWj0HHhEuhkWOslYt2otxhoynzN0n2IaNtRnE3Xm5FYxz7PGtCucSscVOLU5/Y
            hXl8ibVO8OZFHEBhcXGOZ28HdAgEOmEBNlqIaOMkTKQyY2tWux9tU0EhH+Ou+NJ6
            z29cr1PnAVCwO7HoM3BWUqDcmN17VIMmA8PBS93/ACUv0v+9ndBwIGTSiSXfd7PF
            x98nI/aAHrN8aw3FgwyvJOLr/K4IWDJABMLZoPb+ugf7+teA3oGVvO4KiaF2vCUE
            reSYuyUbRO0t/npaL4U5sU8BKrJVdXzVUxI8/70r9Zb6X6zcoc4VuIVyCU3FD0Ue
            kdTXCmVC33ay64dlRF205+5AnIX+8KnqinkLGG1l4I+od7zcpMTOyptMEfuIBuLS
            XgE1LXA+jyEXlRbz0Gf/WrdPepAVwHouFISIbf/jm/Htyvf+w0WyjkVgXOlrgv49
            vxojlqmrKefNASZaNeCvVyAZ5qO2iy5upphhjFn7SAfCEwYBRcfP5HvcHbZLKzM=
            =EgeA
            -----END PGP MESSAGE-----
          fp: 416E502A845A87487EF12661331A5023FC9B89BA
    unencrypted_regex: ^(kind)$
    version: 3.7.1
