---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: self-hosted
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2021-10-13T00-23-17Z

    nameOverride: minio

    env:
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_UPDATE: "off"
      TZ: "Europe/Amsterdam"

    envFrom:
      - secretRef:
          name: minio

    args:
      - server
      - /data
      - --console-address
      - :9001

    service:
      main:
        enabled: true
        ports:
          http:
            enabled: true
            port: 9001
          api:
            enabled: true
            port: 9000

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          cert-manager.io/issue-temporary-certificate: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "backup-restore"
          # traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "minio.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 9001
          - host: "s3.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 9000
        tls:
          - hosts:
              - "minio.${SECRET_DOMAIN}"
              - "s3.${SECRET_DOMAIN}"
            secretName: minio-tls

    metrics:
      serviceMonitor:
        enabled: true

    persistence:
      config:
        enabled: true
        existingClaim: minio
        mountPath: /data

    podAnnotations:
      secret.reloader.stakater.com/reload: "minio"

    # resources:
    #   requests:
    #     memory: 100Mi
    #     cpu: 100m
    #   limits:
    #     memory: 750Mi
