---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: self-hosted
  labels:
#    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 700Gi
  storageClassName: openebs-local
