apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:VG2KpRc1Y8EFbaatXN8r9S10XQvHqgxzRecSOxJIQNzkGALY8oj/Fo+QkR5o6DINavmjOuwOlkBuo/HlSBfKVofjZ7CKLoNeee6vGWwhN3RDA7oiXofMzS7CqBueyXSoKZMFsPJ4jGF/4KKWHK5OHLaBlCtHWgRr,iv:Or84LkEjYhw0Vwl4x3Y4Gph+8x44dcqnuMqO1BWN+2o=,tag:DwwnNf4BOKHkkgxCYgPiSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-07T21:02:02Z"
    mac: ENC[AES256_GCM,data:7aHAA5wS8Qslt64mMSzfReams0dPaZNDylADecToePzpqnHDftWCSteLvSz5ANAaPp4z/ZZBwC5d537KqmRWK4qFdAd/et56Cdeuntkk+ynM+P29ftj1sTKo5mVSJIO3mK7f59fdyqDbAiyYYW0In6tq1hgBZQSXmvWlR/rp+q0=,iv:T4LwQmJ9A364nqUc+hhhLTTC18VbI1KehtxgweQSTPc=,tag:UdeDXxNGbbDzXyYJnd0KkQ==,type:str]
    pgp:
        - created_at: "2021-12-07T21:02:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA452ft8CT80SAQ//dg+NWg6vWiZcUP8QRiRoQ+4JC7ChfaDa9tzbwoTEpFhL
            KwonRUlW+9NIG15bQV3O18UUi4sX+2YFfUuJiW2Rj/jVaul+OV6c67LMUuOZnctA
            V9TL5jMjT/rSWzohhvzXaBS+j596c+uzUu69PNXHMe8NpaPxsEGyQynxDAUL2zHR
            GTg+b1n41FAeP/pAxXfd5QBcPvidM2TeScmtcs8GYg00wOR8R9VmkdntyO2Q38Bj
            XfvaQsUUMNzpci47/SAmw1MVAEgoAPuBhqulMwHOyEcMCTQOPo791ek+DXobpDwv
            EvpdwQdhjxZzJQqw7KBuUVWvFk+y/btuoG6w6Fe/xNueN2oWzlJhOkOhDtBgqwZ7
            79C6oTzqiTM5D7YmA2SaOA9d+ihYcFWOJSZhMsX+544YfRuup+Jzn0Z3HUjQSRTp
            +9a/NHUVbdoKUH38AYUuAwQxy9dAJV/usOpQOGXl8wO5IQFtza8ys3TnsRFh+JPS
            Wt/4dZ0Mvy02fs0MEMxpq7ws3NW1j3CaR8eOWsfvXSiKxc3lgV20s0t4w68w20Nm
            2CZy6Mrag2fa4hHaZnUtu8pLmiSWY58bRYZ+Wu2uMmA3k9fgUiaNDY2fmq6G7jEw
            ZDnIQwgdBmnU+V44F9101uhh1PZXuCg01BeTRBaWhMrykI0fiV1LlgnnGrOwyEjS
            XgHZImHH7DKz2NTbHUuEn0fE1a5DFCj0CsRSKEYDyp51RStbCa3Ltpu6PzJJHFGD
            f/1LyC1h20uo6Y0mBCeEHr2d524xJNtYIpRAu28Uo6NHlAu4v9e6Mbw1RzzEC88=
            =P28x
            -----END PGP MESSAGE-----
          fp: A46BCBE5025D400A71759E6947630974DB001607
        - created_at: "2021-12-07T21:02:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzKiqMukNpUtAQ//UGuRJwvUism2Ja+Bxex7d8WRAN9WM5oTSW37dbRZL965
            +kbl78BVjOJlSuQVSixNal77zxyBPQnjYJrnGPsmZqFSMiiyKGqqUUgGxZfUq4Ge
            LlJJq5qQEQccPYYksfws0/nFRyVIevnHY1LQ7QbdhYi04zmAG6mLYn0C0rutgx45
            pY5i55fEurW01O55GU8PH4nWQnc835YQIPlENu0ZLaEyOFDx26JHU/aZD7DbrTV4
            88aMf5/lhXMVcqc3avfMApuvDxyVpnhVKf0JLZwCMtg/Tt8muxzBjkkvlx4HfoEG
            8nNiN5TJK2qphoKhNr/ZXOoIm7/23F3pNOgB0Nez06++tFLWdIpxsGVlzghTewfZ
            ZikfJEcfjwBNm4rodO/1iBazp61BoXbyB12+ms0Qoku5aOHwwqzDTs2azYLukmq9
            XLZXTATkUj4UpINID7lSaz6aCZcmjs60j8Zm7xImIWHJuwSUOlJJg8+kzj0CBjle
            0cWoBzvRKdDg2QNqY+0hJBk/d8hOoV6+Awx/ll41Yr/3SCTs2Erl+Ms7ouwQqsaV
            l/KD4wtN6CG743FszPyVV8H8QUFOlhyoc9Z6q22eHNAPOxkL+4wVMCvvZXKGBXcK
            kYWU17/WwMWPaek68/K1hVLsIWpBrhqsu9jo1uKtn97WfbuFBDbyRgFOt4H6VV7S
            XgEDkN+ely3kC2AcgiY6dul6XA2Umf17hWcmm7ezLVaoOlRbtt/GCf4Rz3z3cY5w
            YOCZ4Jexj9PmryI4DRVgzPC32cfy6K3EWszFw7YYLsq2f994IANON8CSg8Omzw0=
            =yIy6
            -----END PGP MESSAGE-----
          fp: 416E502A845A87487EF12661331A5023FC9B89BA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
