---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: networking

spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://mojo2600.github.io/pihole-kubernetes/
      chart: pihole
      version: 2.5.3
      sourceRef:
        kind: HelmRepository
        name: pihole-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1

    serviceDns:
      mixedService: false
      type: LoadBalancer
      port: 53
      externalTrafficPolicy: Local
      loadBalancerIP: "${LB_PIHOLE}"
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-dns

    serviceDhcp:
      enabled: false

    serviceWeb:
      http:
        enabled: true
        port: 80
      https:
        enabled: true
        port: 443
      type: ClusterIP

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        cert-manager.io/issue-temporary-certificate: "true"
        hajimari.io/enable: "true"
        hajimari.io/icon: "dns"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - pihole.${SECRET_DOMAIN}
      path: /admin
      tls:
        - hosts:
            - pihole.${SECRET_DOMAIN}
          secretName: "pihole-tls"

    persistentVolumeClaim:
      enabled: true
      existingClaim: "pihole"
      accessModes:
        - ReadWriteOnce
      size: "500Mi"

    admin:
      existingSecret: "pihole"
      passwordKey: "ADMIN_PASSWORD"

    podAnnotations:
      backup.velero.io/backup-volumes: "pihole"
      secret.reloader.stakater.com/reload: "pihole"
