---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: atlassian-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://atlassian.github.io/data-center-helm-charts
  timeout: 3m
