---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: utkuozdemir-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://utkuozdemir.org/helm-charts
  timeout: 3m
